import type { Identity } from './auth.ts';

export type ProjectsEnv = { ASSETS: R2Bucket };

/**
 * A project document is scene metadata only — keyframes, transforms, lights,
 * thumbnail, and the content-addressed keys of its assets. The heavy bytes
 * stay in `a/…` where the CDN serves them, so these stay small enough to move
 * through the Worker directly instead of needing a presigned round trip.
 *
 * The ceiling exists because `thumbnail` is a data URL and therefore the one
 * field that can grow without anybody noticing.
 */
const MAX_DOCUMENT_BYTES = 2 * 1024 * 1024;

const PREFIX = 'p/';

function json(status: number, body: unknown, headers: HeadersInit = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8', ...headers },
  });
}

/** Project ids are generated by `crypto.randomUUID()`; accept nothing else. */
const PROJECT_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export async function handleProjects(
  request: Request,
  env: ProjectsEnv,
  identity: Identity,
  id: string | null,
): Promise<Response> {
  if (id === null) {
    if (request.method !== 'GET') return json(405, { error: 'Method not allowed' });
    return listProjects(env);
  }
  if (!PROJECT_ID.test(id)) return json(400, { error: 'Ungültige Projekt-Id.' });

  switch (request.method) {
    case 'GET':
      return getProject(env, id);
    case 'PUT':
      return putProject(request, env, identity, id);
    case 'DELETE':
      return deleteProject(env, id);
    default:
      return json(405, { error: 'Method not allowed' });
  }
}

/**
 * Lists projects from object metadata alone. Name, author and timestamp live in
 * customMetadata precisely so the dashboard costs one R2 call rather than one
 * per project plus a full JSON parse of each.
 */
async function listProjects(env: ProjectsEnv): Promise<Response> {
  const entries: unknown[] = [];
  let cursor: string | undefined;

  do {
    const page = await env.ASSETS.list({
      prefix: PREFIX,
      cursor,
      include: ['customMetadata'],
    });
    for (const object of page.objects) {
      const meta = object.customMetadata ?? {};
      entries.push({
        id: object.key.slice(PREFIX.length).replace(/\.json$/, ''),
        name: meta.name ?? '(ohne Namen)',
        author: meta.author ?? 'unbekannt',
        updatedAt: Number(meta.updatedAt ?? 0) || object.uploaded.getTime(),
        etag: object.httpEtag,
        size: object.size,
      });
    }
    cursor = page.truncated ? page.cursor : undefined;
  } while (cursor);

  entries.sort((a, b) => (b as { updatedAt: number }).updatedAt - (a as { updatedAt: number }).updatedAt);
  return json(200, { projects: entries });
}

async function getProject(env: ProjectsEnv, id: string): Promise<Response> {
  const object = await env.ASSETS.get(`${PREFIX}${id}.json`);
  if (!object) return json(404, { error: 'Projekt nicht gefunden.' });
  return new Response(object.body, {
    status: 200,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      etag: object.httpEtag,
      // Project documents change; never let a proxy hold one.
      'cache-control': 'no-store',
    },
  });
}

/**
 * Writes a project, refusing to overwrite a version the client has not seen.
 *
 * `If-Match` carries the ETag the editor last read. R2's conditional put turns a
 * concurrent edit into a 409 that the UI can explain, instead of the last tab to
 * autosave silently winning — which, with a 2 s debounce and two people in the
 * same project, is otherwise a matter of time.
 */
async function putProject(
  request: Request,
  env: ProjectsEnv,
  identity: Identity,
  id: string,
): Promise<Response> {
  const raw = await request.arrayBuffer();
  if (raw.byteLength === 0) return json(400, { error: 'Leerer Body.' });
  if (raw.byteLength > MAX_DOCUMENT_BYTES) {
    return json(413, { error: 'Projekt-Dokument ist zu groß.' });
  }

  let document: { project?: { name?: unknown; updatedAt?: unknown } };
  try {
    document = JSON.parse(new TextDecoder().decode(raw));
  } catch {
    return json(400, { error: 'Body ist kein gültiges JSON.' });
  }
  const name = typeof document.project?.name === 'string' ? document.project.name : '(ohne Namen)';

  const key = `${PREFIX}${id}.json`;
  const ifMatch = request.headers.get('If-Match');

  // No If-Match means "this project is new". Checking first keeps an accidental
  // second create from wiping the first; the window between head and put is a
  // race we accept, because both writers are then the same person on the same
  // project in two tabs, and the next autosave carries an ETag.
  if (!ifMatch) {
    const existing = await env.ASSETS.head(key);
    if (existing) {
      return json(409, {
        error: 'Projekt existiert bereits remote – erst laden, dann speichern.',
        etag: existing.httpEtag,
      });
    }
  }

  const written = await env.ASSETS.put(key, raw, {
    httpMetadata: { contentType: 'application/json; charset=utf-8', cacheControl: 'no-store' },
    customMetadata: {
      name,
      author: identity.name,
      updatedAt: String(Date.now()),
    },
    ...(ifMatch ? { onlyIf: { etagMatches: ifMatch.replace(/^W\//, '').replace(/"/g, '') } } : {}),
  });

  // A conditional put whose precondition failed resolves to null rather than
  // throwing — that is the concurrent-edit case.
  if (written === null) {
    const current = await env.ASSETS.head(key);
    return json(409, {
      error: 'Projekt wurde zwischenzeitlich woanders geändert.',
      etag: current?.httpEtag,
      author: current?.customMetadata?.author,
    });
  }

  return json(200, { etag: written.httpEtag, author: identity.name, updatedAt: Date.now() });
}

async function deleteProject(env: ProjectsEnv, id: string): Promise<Response> {
  // Assets are intentionally left behind: they are content-addressed and may be
  // shared with another project or with an embed that is still live on a
  // customer site. Orphan cleanup is a separate, deliberate job.
  await env.ASSETS.delete(`${PREFIX}${id}.json`);
  return new Response(null, { status: 204 });
}
