import type { Identity } from './auth.ts';
import { invalidateUsage } from './quota.ts';

export type ProjectsEnv = { ASSETS: R2Bucket };

/**
 * A project document is scene metadata only — keyframes, transforms, lights,
 * thumbnail, and the content-addressed keys of its assets. The heavy bytes
 * stay in `a/…` where the CDN serves them, so these stay small enough to move
 * through the Worker directly instead of needing a presigned round trip.
 *
 * The ceiling exists because `thumbnail` is a data URL and therefore the one
 * field that can grow without anybody noticing.
 */
const MAX_DOCUMENT_BYTES = 2 * 1024 * 1024;

const PREFIX = 'p/';

function json(status: number, body: unknown, headers: HeadersInit = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8', ...headers },
  });
}

/** Project ids are generated by `crypto.randomUUID()`; accept nothing else. */
const PROJECT_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export async function handleProjects(
  request: Request,
  env: ProjectsEnv,
  identity: Identity,
  id: string | null,
): Promise<Response> {
  if (id === null) {
    if (request.method !== 'GET') return json(405, { error: 'Method not allowed' });
    return listProjects(env);
  }
  if (!PROJECT_ID.test(id)) return json(400, { error: 'Ungültige Projekt-Id.' });

  switch (request.method) {
    case 'GET':
      return getProject(env, id);
    case 'PUT':
      return putProject(request, env, identity, id);
    case 'DELETE':
      return deleteProject(env, id);
    default:
      return json(405, { error: 'Method not allowed' });
  }
}

/**
 * Lists projects from object metadata alone. Name, author and timestamp live in
 * customMetadata precisely so the dashboard costs one R2 call rather than one
 * per project plus a full JSON parse of each.
 */
async function listProjects(env: ProjectsEnv): Promise<Response> {
  const entries: unknown[] = [];
  let cursor: string | undefined;

  do {
    const page = await env.ASSETS.list({
      prefix: PREFIX,
      cursor,
      include: ['customMetadata'],
    });
    for (const object of page.objects) {
      const meta = object.customMetadata ?? {};
      entries.push({
        id: object.key.slice(PREFIX.length).replace(/\.json$/, ''),
        name: meta.name ?? '(ohne Namen)',
        author: meta.author ?? 'unbekannt',
        updatedAt: Number(meta.updatedAt ?? 0) || object.uploaded.getTime(),
        etag: object.httpEtag,
        size: object.size,
      });
    }
    cursor = page.truncated ? page.cursor : undefined;
  } while (cursor);

  entries.sort((a, b) => (b as { updatedAt: number }).updatedAt - (a as { updatedAt: number }).updatedAt);
  return json(200, { projects: entries });
}

async function getProject(env: ProjectsEnv, id: string): Promise<Response> {
  const object = await env.ASSETS.get(`${PREFIX}${id}.json`);
  if (!object) return json(404, { error: 'Projekt nicht gefunden.' });
  return new Response(object.body, {
    status: 200,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      etag: object.httpEtag,
      // Project documents change; never let a proxy hold one.
      'cache-control': 'no-store',
    },
  });
}

/**
 * Writes a project, refusing to overwrite a version the client has not seen.
 *
 * `If-Match` carries the ETag the editor last read. R2's conditional put turns a
 * concurrent edit into a 409 that the UI can explain, instead of the last tab to
 * autosave silently winning — which, with a 2 s debounce and two people in the
 * same project, is otherwise a matter of time.
 */
async function putProject(
  request: Request,
  env: ProjectsEnv,
  identity: Identity,
  id: string,
): Promise<Response> {
  const raw = await request.arrayBuffer();
  if (raw.byteLength === 0) return json(400, { error: 'Leerer Body.' });
  if (raw.byteLength > MAX_DOCUMENT_BYTES) {
    return json(413, { error: 'Projekt-Dokument ist zu groß.' });
  }

  let document: { project?: { name?: unknown; updatedAt?: unknown } };
  try {
    document = JSON.parse(new TextDecoder().decode(raw));
  } catch {
    return json(400, { error: 'Body ist kein gültiges JSON.' });
  }
  const name = typeof document.project?.name === 'string' ? document.project.name : '(ohne Namen)';

  const key = `${PREFIX}${id}.json`;
  const ifMatch = request.headers.get('If-Match');

  // No If-Match means "this project is new". Checking first keeps an accidental
  // second create from wiping the first; the window between head and put is a
  // race we accept, because both writers are then the same person on the same
  // project in two tabs, and the next autosave carries an ETag.
  if (!ifMatch) {
    const existing = await env.ASSETS.head(key);
    if (existing) {
      return json(409, {
        error: 'Projekt existiert bereits remote – erst laden, dann speichern.',
        etag: existing.httpEtag,
      });
    }
  }

  const written = await env.ASSETS.put(key, raw, {
    httpMetadata: { contentType: 'application/json; charset=utf-8', cacheControl: 'no-store' },
    customMetadata: {
      name,
      author: identity.name,
      updatedAt: String(Date.now()),
    },
    ...(ifMatch ? { onlyIf: { etagMatches: ifMatch.replace(/^W\//, '').replace(/"/g, '') } } : {}),
  });

  // A conditional put whose precondition failed resolves to null rather than
  // throwing — that is the concurrent-edit case.
  if (written === null) {
    const current = await env.ASSETS.head(key);
    return json(409, {
      error: 'Projekt wurde zwischenzeitlich woanders geändert.',
      etag: current?.httpEtag,
      author: current?.customMetadata?.author,
    });
  }

  return json(200, { etag: written.httpEtag, author: identity.name, updatedAt: Date.now() });
}

/** Content-addressed asset, e.g. `a/1a2b3c4d5e6f7a8b.glb`. Nothing else. */
const ASSET_KEY = /^a\/[0-9a-f]{16}\.[a-z0-9]+$/;

/**
 * The asset keys one project document points at.
 *
 * Deliberately narrow: only the two places the editor writes a key, and only
 * values that look like one. A document is client-written JSON, and this list
 * decides what gets deleted, so a malformed or hostile field must not be able
 * to name `p/…` or `w/…`.
 */
function collectAssetKeys(document: unknown): string[] {
  const doc = document as {
    project?: { environment?: { assetKey?: unknown } | null };
    models?: Array<{ assetKey?: unknown } | null>;
  };
  const keys: string[] = [];

  const environment = doc?.project?.environment?.assetKey;
  if (typeof environment === 'string' && ASSET_KEY.test(environment)) keys.push(environment);

  for (const model of doc?.models ?? []) {
    const key = model?.assetKey;
    if (typeof key === 'string' && ASSET_KEY.test(key)) keys.push(key);
  }
  return keys;
}

/**
 * Every asset key that is still spoken for, read from the surviving project
 * documents.
 *
 * Assets are content-addressed, so the same bytes are one object no matter how
 * many projects use them: duplicating a project, or two people uploading the
 * same GLB, produces shared references. Deleting on the deleted project's word
 * alone would therefore empty a scene somebody else still has open.
 *
 * `complete` is false when a document could not be read. The caller then keeps
 * every asset, because a partial reference list is indistinguishable from an
 * asset nobody uses.
 *
 * Costs one read per project. That is a subrequest each, which is why this runs
 * on delete and nowhere else.
 */
async function referencedAssets(env: ProjectsEnv): Promise<{ keys: Set<string>; complete: boolean }> {
  const keys = new Set<string>();
  let complete = true;
  let cursor: string | undefined;

  do {
    const page = await env.ASSETS.list({ prefix: PREFIX, cursor });
    for (const entry of page.objects) {
      const object = await env.ASSETS.get(entry.key);
      // Vanished between list and get: then it references nothing any more.
      if (!object) continue;
      try {
        for (const key of collectAssetKeys(await object.json())) keys.add(key);
      } catch {
        complete = false;
      }
    }
    cursor = page.truncated ? page.cursor : undefined;
  } while (cursor);

  return { keys, complete };
}

/**
 * Deletes the project and the assets that only it used.
 *
 * This is the only lever against a bucket that otherwise just grows: with a
 * quota in place, assets that outlive their project are space nobody can ever
 * reclaim. It is destructive beyond this studio, an embed on a customer site
 * loads its model from these keys and will break, which is why the dashboard
 * makes you type the word first.
 */
async function deleteProject(env: ProjectsEnv, id: string): Promise<Response> {
  const key = `${PREFIX}${id}.json`;
  const object = await env.ASSETS.get(key);
  if (!object) return json(200, { deletedAssets: 0, keptAssets: 0, freedBytes: 0 });

  const documentBytes = object.size;
  let own: string[] = [];
  try {
    own = collectAssetKeys(await object.json());
  } catch {
    // An unreadable document names no assets we can act on. Delete the document
    // itself anyway, otherwise the project is undeletable.
    own = [];
  }

  await env.ASSETS.delete(key);
  const unique = [...new Set(own)];

  // Read the survivors after the delete, so the project being removed cannot
  // count as a reference to its own assets.
  const { keys: stillUsed, complete } = unique.length > 0
    ? await referencedAssets(env)
    : { keys: new Set<string>(), complete: true };

  const orphans = complete ? unique.filter((k) => !stillUsed.has(k)) : [];

  let freedBytes = documentBytes;
  for (const orphan of orphans) {
    const head = await env.ASSETS.head(orphan);
    if (head) freedBytes += head.size;
  }
  if (orphans.length > 0) await env.ASSETS.delete(orphans);

  // The measurement behind the storage meter is now wrong in the one direction
  // people notice: it would keep reporting space that was just freed.
  invalidateUsage();

  return json(200, {
    deletedAssets: orphans.length,
    keptAssets: unique.length - orphans.length,
    freedBytes,
    ...(complete ? {} : { incomplete: true }),
  });
}
